# Auto update
auto-update: true
# Enable debug logs
debug: false
# Enable trades (Set this to true to enable the trades)
# This option is to make sure you read through the config options.
enable-trades: false
