name: VillagerTrade
version: '${project.version}'
main: net.guizhanss.villagertrade.VillagerTrade
api-version: 1.16
depend: [ Slimefun ]
softdepend:
  - GuizhanLibPlugin
  - ColoredEnderChests
  - DyedBackpacks
  - EcoPower
  - ElectricSpawners
  - ExoticGarden
  - ExtraGear
  - ExtraHeads
  - HotbarPets
  - luckyblocks-sf
  - PrivateStorage
  - SlimefunOreChunks
  - SlimyTreeTaps
  - SoulJars
  - CommandOverride
  - EmeraldEnchants2
  - QuickMarket
  - QuickSell
  - RankPrefixPlus
  - LiteXpansion
  - MobCapturer
  - SoundMuffler
  - ExtraTools
  - TranscEndence
  - Liquid
  - SFCalc
  - SlimefunWarfare
  - Slimy-Power-Suits
  - FluffyMachines
  - SlimyRepair
  - InfinityExpansion
  - FoxyMachines
  - GlobalWarming
  - DynaTech
  - GeneticChickengineering
  - HeadLimiter
  - SlimeXpansion
  - Barrels
  - ClayTech
  - FNAmplifications
  - SMG
  - EMC2
  - Simple-Storage
  - AlchimiaVitae
  - SlimeTinker
  - PotionExpansion
  - FlowerPower
  - Galactifun
  - Element-Manipulation
  - CrystamaeHistoria
  - DankTech2
  - Networks
  - VillagerUtil
  - MissileWarfare
  - SensibleToolbox
  - Endrex
  - Bump
  - FinalTech
  - FutureTech
  - GuizhanCraft
  - CrispyMachine
  - DimensionTraveler
  - Chocohills
  - draconic
  - RandomExpansion
  - ExLimus
  - MoneyAndThings
  - SlimyBees
  - GeneticManipulation
  - NotEnoughAddons
  - SlimeSec
  - EMCTech
authors: [ ybw0014 ]
description: A Slimefun addon that allow slimefun items to be added to villager trades.
