blank_issues_enabled: false
contact_links:
  - name: 没有 Github 账号? 不会使用 Github?
    url: https://ybw0014.net/go/sf-qgroup
    about: 点击右侧按钮加入QQ群进行反馈
  - name: Join Slimefun Addon Community Discord
    url: https://discord.gg/SqD3gg5SAU
    about: Feel free to provide suggestions and feedback in discord!
