name: Blob Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: VillagerTrade
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
